[package]
name = "websocket_events"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
axum-macros = "0.4.1"
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
shuttle-axum = "0.40.0"
shuttle-runtime = "0.40.0"
tokio = "1.28.2"
tracing = "0.1.40"
